export const services = [
  {
    id: 'taglio-shampoo',
    name: 'Taglio Capelli + Shampoo',
    description: 'Taglio personalizzato con shampoo lavante e finitura.',
    price: '15€',
    duration: '30 min',
  },
  {
    id: 'taglio-bambini',
    name: 'Taglio Bambini (1-7 anni)',
    description: 'Taglio dedicato ai più piccoli, con pazienza e cura.',
    price: '13€',
    duration: '30 min',
  },
  {
    id: 'taglio-barba',
    name: 'Taglio Capelli + Barba',
    description: 'Servizio completo: taglio capelli e sistemazione della barba.',
    price: '22€',
    duration: '60 min',
  },
  {
    id: 'taglio-tattoo',
    name: 'Taglio + Design Tattoo',
    description: 'Taglio con disegno personalizzato realizzato a mano libera.',
    price: '20€',
    duration: '60 min',
  },
  {
    id: 'rasatura-classica',
    name: 'Rasatura Classica della Barba',
    description: 'Rasatura tradizionale con asciugamano caldo e rasoio da barbiere.',
    price: '7€',
    duration: '20 min',
  },
  {
    id: 'taper-fade',
    name: 'Taper Fade',
    description: 'Sfumatura graduale e precisa, stile moderno e pulito.',
    price: '15€',
    duration: '45 min',
  },
  {
    id: 'barba-pigmentazione',
    name: 'Barba + Pigmentazione',
    description: 'Sistemazione barba con pigmentazione per riempire i vuoti.',
    price: '10€',
    duration: '30 min',
  },
  {
    id: 'disegno-barba',
    name: 'Disegno della Barba',
    description: 'Definizione e disegno della barba con linee perfette.',
    price: '7€',
    duration: '20 min',
  },
  {
    id: 'servizio-vip',
    name: 'Servizio Completo VIP',
    description: 'Esperienza premium: taglio, barba, styling e finitura di lusso.',
    price: '30€',
    duration: '90 min',
  },
  {
    id: 'depilazione-sopracciglia',
    name: 'Depilazione Sopracciglia',
    description: 'Rifinitura e depilazione delle sopracciglia con pinzetta.',
    price: '5€',
    duration: '10 min',
  },
  {
    id: 'taglio-meches',
    name: 'Taglio + Meches',
    description: 'Taglio con schiariture personalizzate per un look unico.',
    price: '70€',
    duration: '120 min',
  },
  {
    id: 'taglio-total-white',
    name: 'Taglio + Total White',
    description: 'Trasformazione completa con decolorazione totale e taglio.',
    price: '100€',
    duration: '150 min',
    image: '/service-total-white.jpg',
  },
  {
    id: 'shampoo',
    name: 'Shampoo',
    description: 'Shampoo lavante. Servizio gratuito.',
    price: 'Gratis',
    duration: '10 min',
  },
];

export const team = [
  {
    id: 'franco',
    name: 'Jesús Franco',
    role: 'Fondatore & Master Barber',
    bio: 'Oltre 12 anni a perfezionare l\'arte del barbiere. Specializzato in tagli classici e tecniche di rasoio.',
    image: '/team-jesus-franco.jpg',
    specialties: ['Taglio Classico', 'Rasoio', 'Fade'],
  },
  {
    id: 'marcos',
    name: 'Emilia Nava',
    role: 'Senior Barber',
    bio: 'Esperto di stili moderni e sfumature. Formato nelle migliori barberie di Milano e Londra.',
    image: '/team-emilia-nava.jpg',
    specialties: ['Skin Fade', 'Beard Design', 'Textured Cuts'],
  },
  {
    id: 'daniel',
    name: 'Jesús Morillo',
    role: 'Barber',
    bio: 'Padroneggia lo stile urbano e i tagli strutturati. Appassionato di tendenze e dettagli.',
    image: '/team-jesus-morillo.jpg',
    specialties: ['Tagli Moderni', 'Disegno Linee', 'Styling'],
  },
];

export const products = [
  {
    id: 'pomada-mate',
    name: 'Pomada Mate',
    description: 'Tenuta forte con finitura opaca naturale. Ideale per look strutturati.',
    price: 18,
    image: 'https://picsum.photos/seed/franco-pomade/600/450',
    category: 'Styling',
  },
  {
    id: 'aceite-barba',
    name: 'Aceite para Barba',
    description: 'Idrata, ammorbidisce e dona lucentezza alla barba. Profumo cedro e sandalo. 30ml.',
    price: 22,
    image: 'https://picsum.photos/seed/franco-beardoil/600/450',
    category: 'Barba',
  },
  {
    id: 'cera-modeladora',
    name: 'Cera Modeladora',
    description: 'Cera modellante a tenuta media, senza residui. Perfetta per definire lo stile. 100ml.',
    price: 16,
    image: 'https://picsum.photos/seed/franco-wax/600/450',
    category: 'Styling',
  },
  {
    id: 'shampoo-premium',
    name: 'Shampoo Premium',
    description: 'Formula delicata con cheratina e biotina. Rinforza e nutre il capello.',
    price: 20,
    image: 'https://picsum.photos/seed/franco-shampoo/600/450',
    category: 'Cura',
  },
  {
    id: 'kit-completo',
    name: 'Kit Completo',
    description: 'Set regalo con i prodotti essenziali per la cura di capelli e barba.',
    price: 55,
    image: 'https://picsum.photos/seed/franco-kit/600/450',
    category: 'Kit',
  },
];

export const contact = {
  address: 'Via del Corso 24, Milano',
  phone: '+39 02 1234 5678',
  email: 'ciao@francobarberstudio.it',
  hours: [
    { day: 'Lunedì – Venerdì', time: '09:00 – 20:00' },
    { day: 'Sabato', time: '10:00 – 18:00' },
    { day: 'Domenica', time: 'Chiuso' },
  ],
  instagram: 'https://instagram.com/francobarberstudio',
};
